#!/usr/bin/with-contenv bash

 echo "Installing Build Packages" && \
    apk add --no-cache --virtual=build-dependencies \
        g++ gcc make py3-pip python3-dev

 echo "Installing Packages" && \
   apk add --update --no-cache \
       g++ gcc make python3-dev \
       curl jq py3-openssl py3-setuptools \
       python3 py-tz py-dateutil bash \
       gcc musl-dev py3-pip \
       libxslt-dev libxml2-dev py3-virtualenv \
       coreutils curl  git \
       openssl tar tzdata vnstat wget

  echo "Installing Packages [1/3]" && \
  pip3 install --no-cache-dir -U \
  pip && \
  pip3 install --no-cache-dir -U \
  plexapi \
  pycryptodomex \
  pytz \
  tzlocal \
  pip-tools \
  CherryPy \
  Mako \
  arrow \
  portend \
  APScheduler \
  configobj \
  urllib3 \
  passlib \
  requests \
  infi.systray \
  oauthlib \
  xmltodict \
  websocket-client \
  geoip2 \
  pyjwt \
  logutils \
  maxminddb \
  cloudinary \
  facebook-sdk \
  python-twitter \
  ipwhois \
  IPy \
  vnstat \
  wget

  echo "Installing Packages [2/3]" && \
  pip3 install --no-cache-dir -U \
  pip && \
  pip3 install --no-cache-dir -U \
  plexapi \
  pycryptodomex \
  pytz \
  tzlocal \
  pip-tools \
  CherryPy \
  Mako \
  arrow \
  portend \
  APScheduler \
  configobj \
  urllib3 \
  passlib \
  requests \
  infi.systray \
  oauthlib \
  xmltodict \
  websocket-client \
  geoip2 \
  pyjwt \
  logutils \
  maxminddb \
  cloudinary \
  facebook-sdk \
  python-twitter \
  ipwhois \
  IPy \
  bs4 \
  feedparser \
  httpagentparser \
  bleach \
  paho-mqtt \
  gntp \
  PyNMA \
  profilehooks \
  distro \
  pyopenssl

 echo "Installing Packages [3/3]" && \
    python3 -m pip install virtualenv
    python3 -m venv /app/tautulli
    source /app/tautulli/bin/activate
